services:
    #mariadb:
    #    image: mariadb:11
    #    environment:
    #        MARIADB_ROOT_PASSWORD: rootpassword
    #        MARIADB_DATABASE: mydatabase
    #        MARIADB_USER: myuser
    #        MARIADB_PASSWORD: mypassword
    #    volumes:
    #        - mariadb_data:/var/lib/mysql
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - hotels_cfapp
            - houses_cfapp
volumes:
    mariadb_data:
    shared_data:
