#!/bin/bash

function help(){
    echo ''
    echo '--------------------------------------------------------------------------------------------------'
    echo ' Commands you can use.                                                                            '
    echo '--------------------------------------------------------------------------------------------------'
    echo ' app:start                                                                                        '
    echo ' app:stop                                                                                         '
    echo ' app:update                                                                                       '
    echo ' build:containers      ./appcli cli:build:containers                                              '
    echo ' config                ./appcli cli:site:config {default.domain}                                  '
    echo ' config:find           ./appcli cli:site:config {default.domain} | jq ".[] | {string}"            '
    echo ' create                ./appcli cli:site:creation {default.domain}                                '
    echo ' domains:add           ./appcli cli:site:domains:add {default.domain}                             '
    echo ' domains:list          ./appcli cli:site:domains:list {default.domain}                            '
    echo ' domains:list:users    ./appcli cli:site:domains:list:user {default.domain}                       '
    echo ' domains:list:search   ./appcli cli:site:domains:list:search {search_string}                      '
    echo ' item:add              ./appcli cli:site:item:add {default.domain} {environment} {json_string}    '
    echo ' item:update           ./appcli cli:site:item:update {default.domain} {environment} {json_string} '
    echo ' item:remove           ./appcli cli:site:item:remove {default.domain} {environment} {json_string} '
    echo '--------------------------------------------------------------------------------------------------'
    echo ''
}

path=$(pwd)
config_path=$path'/../hosting/config/containers'

if [[ "$1" == "build:containers" ]]; then
   ./appcli cli:build:containers

elif [[ "$1" == "app:start" ]]; then
  bash "$(pwd)/../hosting/config/containers/start.sh" "$config_path"

elif [[ "$1" == "app:stop" ]]; then
  bash "$(pwd)/../hosting/config/containers/stop.sh" "$config_path"

elif [[ "$1" == "app:update" ]]; then
  bash "$(pwd)/maintain.sh" "$2"

elif [[ "$1" == "config" ]]; then
  ./appcli cli:site:config $2

elif [[ "$1" == "config:find" ]]; then
  ./appcli cli:site:config $2 | jq ".[] | $3"

elif [ "$1" == "create" ]; then
  ./appcli cli:site:creation $2

elif [[ "$1" == "domains:add" ]]; then
   ./appcli cli:site:domains:add $2
   
elif [[ "$1" == "domains:list" ]]; then
  ./appcli cli:site:domains:list $2

elif [[ "$1" == "domains:list:users" ]]; then
  ./appcli cli:site:domains:list:users $2

elif [[ "$1" == "domains:list:search" ]]; then
  ./appcli cli:site:domains:list:search $2

elif [ "$1" == "item:add" ]; then
  ./appcli cli:site:item:add $2 $3 $4

elif [ "$1" == "item:update" ]; then
  ./appcli cli:site:item:update $2 $3 $4

elif [ "$1" == "item:remove" ]; then
  ./appcli cli:site:item:remove $2 $3 $4

else
  help
fi
