#!/bin/bash

function help(){
    echo ''
    echo '---------------------------------------------------------------------------------------------'
    echo ' Commands you can use.                                                                       '
    echo '---------------------------------------------------------------------------------------------'
    echo ' domains:add   ./sitenpro spro:site:domains:add {default.domain}                             '
    echo ' domains:list  ./sitenpro spro:site:domains:list                                             '
    echo ' config        ./sitenpro spro:site:config {default.domain}                                  '
    echo ' config:find   ./sitenpro spro:site:config {default.domain} | jq ".[] | {string}"            '
    echo ' create        ./sitenpro spro:site:creation {default.domain}                                '
    echo ' item:add      ./sitenpro spro:site:item:add {default.domain} {environment} {json_string}    '
    echo ' item:update   ./sitenpro spro:site:item:update {default.domain} {environment} {json_string} '
    echo ' item:remove   ./sitenpro spro:site:item:remove {default.domain} {environment} {json_string} '
    echo '---------------------------------------------------------------------------------------------'
    echo ''
}

if [[ "$1" == "domains:add" ]]; then
   ./sitenpro spro:site:domains:add "$2"
   
elif [[ "$1" == "domains:list" ]]; then
  ./sitenpro spro:site:domains:list

elif [[ "$1" == "config" ]]; then
  ./sitenpro spro:site:config "$2"

elif [[ "$1" == "config:find" ]]; then
  ./sitenpro spro:site:config $2 | jq ".[] | $3"

elif [ "$1" == "create" ]; then
  ./sitenpro spro:site:creation "$2"

elif [ "$1" == "item:add" ]; then
  ./sitenpro spro:site:item:add "$2" "$3" "$4"

elif [ "$1" == "item:update" ]; then
  ./sitenpro spro:site:item:update "$2" "$3" "$4"

elif [ "$1" == "item:remove" ]; then
  ./sitenpro spro:site:item:remove "$2" "$3" "$4"

else
  help
fi
